Allow building a static lib
narugit/smctemp pull request #19
Opened 2023-09-12 09:35 UTC by enen92

Hey @narugit, thanks for merging the gpu PR.
This is my last PR on the queue. I understand if you don't think it is of any value since it's pretty external to the tool (since it is a cli tool/executable). Regardless, I think it's better to push it upstream instead of carrying the patch around (and it is really small anyway).

It allows to build the project (except the executable) as a static library so that it can be included/linked in external software. With this I can include it as a dependency on Kodi and replace our old smc code (which I plan to do this week - have a small PoC that needs cleanup).

I'd ask you to please tag a new version/release after this one is merged (or refused) since it is easier for us to control the source tarballs on the mirrors.

Thanks for all your help with the recent PRs

2023-09-12 09:38 UTC, enen92 commented
Kodi PoC: https://github.com/xbmc/xbmc/commit/35729b97aa7e1f2868a059f7810fea67777dad0e
(still using an old version of one of my branches)

2023-09-14 23:53 UTC, narugit requested changes
Thank you for the suggestion. I'm in favor of adding the option to generate a static library to make it easier to port to other modules.

I haven't been differentiating between `:=` and `=` in my Makefiles so far, but I'm considering a reevaluation as part of this PR. To ensure a reliable build with this Makefile, I'm leaning towards using `:=` exclusively unless there's a spetial reason not to. In the previous Makefiles, even `CXX` was assigned using `=`, but I plan to switch it to `:=` after this PR.

2023-09-14 23:53 UTC, narugit commented on Makefile
> +OBJS= smctemp.o \
```suggestion
OBJS := smctemp.o \
```

2023-09-14 23:53 UTC, narugit commented on Makefile
> +HEADERS = smctemp.h \
```suggestion
HEADERS := smctemp.h \
```

2023-09-14 23:53 UTC, narugit commented on Makefile
> +LIB = libsmctemp.a
```suggestion
STATIC_LIB := libsmctemp.a
```

2023-09-15 23:55 UTC, narugit approved these changes
LGTM

2023-09-15 23:55 UTC, merged

2023-09-16 00:02 UTC, narugit commented
@enen92 
I've created 0.2.0 release.
https://github.com/narugit/smctemp/releases/tag/0.2.0